---
- hosts: myserver
  become: yes
  
  vars:
    - WORKSPACE: ""
    
  tasks:
    - name: ensure nginx is at the latest version
      shell: apt clean && apt update && apt upgrade -y && apt install nginx -y
      
    - name: Copy Website index.html to application server
      copy:
        src: "{{WORKSPACE}}/devops-training/nginx-website/index.html"
        dest: "/var/www/html"
    - name: start nginx
      service:
          name: nginx
          state: started
