---
- hosts: myserver
  become: yes
  tasks:
    - name: ensure nginx is at the latest version
      shell: sudo apt clean && sudo apt update && sudo apt upgrade -y && sudo apt install nginx -y
    - name: start nginx
      service:
          name: nginx
          state: started
